// Generated by CoffeeScript 1.10.0
var Backbone, Codex, Codices,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Backbone = require("backbone");

Codex = require("../models/codex");

Codices = (function(superClass) {
  extend(Codices, superClass);

  function Codices() {
    return Codices.__super__.constructor.apply(this, arguments);
  }

  Codices.prototype.model = Codex;

  return Codices;

})(Backbone.Collection);

module.exports = new Codices();
