// Generated by CoffeeScript 1.10.0
var Backbone, Text, Texts, _, dropdownOptions,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Backbone = require('backbone');

_ = require("underscore");

Text = require('../models/text-listitem');

dropdownOptions = require("../views/codex/edit/form/dropdown/options");

Texts = (function(superClass) {
  extend(Texts, superClass);

  function Texts() {
    return Texts.__super__.constructor.apply(this, arguments);
  }

  Texts.prototype.model = Text;

  Texts.prototype.initialize = function() {
    _.extend(this, dropdownOptions);
    return this.dropdownOptionsInitialize();
  };

  Texts.prototype.comparator = function(model) {
    return model.get('title');
  };

  return Texts;

})(Backbone.Collection);

module.exports = new Texts();
