// Generated by CoffeeScript 1.10.0
var Backbone, Config, backendUrl,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Backbone = require('backbone');

backendUrl = "http://demo17.huygens.knaw.nl/test-marginal-scholarship-backend/";

Config = (function(superClass) {
  extend(Config, superClass);

  function Config() {
    return Config.__super__.constructor.apply(this, arguments);
  }

  Config.prototype.defaults = function() {
    return {
      backendUrl: backendUrl,
      personsUrl: backendUrl + "lists/person",
      fullPersonUrl: backendUrl + "persons",
      usersUrl: backendUrl + "users",
      meUrl: backendUrl + "current_session/user",
      textsUrl: backendUrl + "lists/text",
      fullTextUrl: backendUrl + "texts",
      localitiesUrl: backendUrl + "localityhierarchy",
      facsimileUrl: "https://cdn.huygens.knaw.nl/marginal-scholarship/images/"
    };
  };

  return Config;

})(Backbone.Model);

module.exports = new Config();
